project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: /src/_locales/en/messages.json
    translation: /src/_locales/%two_letters_code%/messages.json
    dest: /messages.json
    languages_mapping:
      two_letters_code:
        pt-BR: pt_BR
        zh-CN: zh_CN
        zh-TW: zh_TW

  - source: /README.md
    translation: /README.%two_letters_code%.md
    dest: /README.md
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        zh-CN: zh-CN
        zh-TW: zh-TW
