project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: /src/_locales/en/messages.json
    translation: /src/_locales/%two_letters_code%/messages.json
    dest: /messages.json
    languages_mapping:
      two_letters_code:
        pt-BR: pt_BR
        zh-CN: zh_CN
        zh-TW: zh_TW
    skip_untranslated_strings: true

  - source: /web-store-assets/en/description.txt
    translation: /web-store-assets/%two_letters_code%/description.txt
    dest: /store/description.txt
    languages_mapping: &languages_mapping_hyphen
      two_letters_code:
        pt-BR: pt-BR
        zh-CN: zh-CN
        zh-TW: zh-TW

  - source: /web-store-assets/en/chrome-screenshot-*.png
    translation: /web-store-assets/%two_letters_code%/%original_file_name%
    dest: /store/chrome/screenshots/%original_file_name%
    languages_mapping: *languages_mapping_hyphen
    skip_untranslated_files: true

  - source: /README.md
    translation: /README.%two_letters_code%.md
    dest: /README.md
    languages_mapping: *languages_mapping_hyphen
