name: Check
on:
  pull_request:
    branches:
      - master
  workflow_dispatch: {}
permissions: {}
defaults:
  run:
    shell: bash
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check by Biome
        run: pnpm biome ci --formatter-enabled=false --reporter=github

      - name: Check by Prettier
        # Allow formatting issues (exit code 1) but fail on syntax errors (exit code 2).
        run: pnpm prettier --check '**/*.{html,yml,yaml,md}' || (( $? == 1 ))

      - name: Check by TypeScript
        run: pnpm tsc --build

      - name: Test
        run: pnpm test

      - name: Build
        run: |
          pnpm build
          pnpm build --browser firefox
          pnpm build --browser safari
        env:
          DROPBOX_API_KEY: ${{ secrets.DROPBOX_API_KEY }}
          DROPBOX_API_SECRET: ${{ secrets.DROPBOX_API_SECRET }}
          GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          GOOGLE_DRIVE_API_SECRET: ${{ secrets.GOOGLE_DRIVE_API_SECRET }}
