name: Check

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Check
        run: pnpm check-ci

      - name: Test
        run: pnpm test

      - name: Build
        run: |
          pnpm build
          pnpm build --browser firefox
          pnpm build --browser safari
        env:
          DROPBOX_API_KEY: ${{ secrets.DROPBOX_API_KEY }}
          DROPBOX_API_SECRET: ${{ secrets.DROPBOX_API_SECRET }}
          GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          GOOGLE_DRIVE_API_SECRET: ${{ secrets.GOOGLE_DRIVE_API_SECRET }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: dist
          path: dist

      - name: "[Website] Get changed files"
        id: website-changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files: website/**

      - name: "[Website] Check"
        if: steps.website-changed-files.outputs.any_changed == 'true'
        run: pnpm check
        working-directory: website

      - name: "[Website] Build"
        if: steps.website-changed-files.outputs.any_changed == 'true'
        run: pnpm build
        working-directory: website
