name: Crowdin

on:
  workflow_dispatch: {}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.PULL_REQUEST_TOKEN }}

      - name: Crowdin
        uses: crowdin/github-action@9787f4fcb6a8450929673f1e8db841e8a5c35a2f # v2.10.0
        with:
          download_translations: true
          export_only_approved: true
          pull_request_base_branch_name: master
        env:
          GITHUB_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
