name: Format
on:
  push:
    branches:
      - master
  workflow_dispatch: {}
permissions: {}
defaults:
  run:
    shell: bash
jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Format by Biome
        run: pnpm biome format --write

      - name: Format by Prettier
        run: pnpm prettier --write '**/*.{html,yml,yaml,md}'

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add .
            git commit -m "style: format by biome and prettier [skip ci]"
            git push
          fi
