name: "[Website] Deploy"

permissions:
  contents: read
  id-token: write
  pages: write

on:
  push:
    branches:
      - master
    paths:
      - website/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Build
        run: pnpm build
        working-directory: website

      - name: Upload
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: website/build
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
